[package]
name = "purs"
version = "0.1.0"
authors = ["Xavier Cambar <xcambar@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
clap = "2.33"
dirs = "2.0.2"
git2 = "0.8"
regex = "1.1.6"
tico = "1.0.0"
