[package]
authors = ["Xavier Cambar <xcambar@gmail.com>"]
name = "purs"
version = "0.1.0"

[dependencies]
ansi_term = "0.11"
clap = "2.33.0"
git2 = "0.6.11"
regex = "0.2"
tico = "1.0.0"
try_opt = "0.1.1"
